---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dhcp
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - scc.yaml
  - rolebinding.yaml
  - configmap.yaml
  - pod.yaml

